# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Package Verifications

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "std2-all"
            python: "3.7"
            postgres: "17"
          - platform: "std2-all"
            python: "3.8.0"
            postgres: "17"
          - platform: "std2-all"
            python: "3.8"
            postgres: "17"
          - platform: "std2-all"
            python: "3.9"
            postgres: "17"
          - platform: "std2-all"
            python: "3.10"
            postgres: "17"
          - platform: "std2-all"
            python: "3.11"
            postgres: "17"
          - platform: "std2-all"
            python: "3.12"
            postgres: "17"
          - platform: "std2-all"
            python: "3.13"
            postgres: "17"
          - platform: "std2-all"
            python: "3.14"
            postgres: "17"
          - platform: "std"
            python: "3"
            postgres: "10"
          - platform: "std"
            python: "3"
            postgres: "11"
          - platform: "std"
            python: "3"
            postgres: "12"
          - platform: "std"
            python: "3"
            postgres: "13"
          - platform: "std"
            python: "3"
            postgres: "14"
          - platform: "std"
            python: "3"
            postgres: "15"
          - platform: "std"
            python: "3"
            postgres: "16"
          - platform: "std-all"
            python: "3"
            postgres: "17"
          - platform: "std-all"
            python: "3"
            postgres: "18"
          - platform: "ubuntu_24_04"
            python: "3"
            postgres: "17"
          - platform: "altlinux_10"
            python: "3"
            postgres: "17"
          - platform: "altlinux_11"
            python: "3"
            postgres: "17"

    steps:
    - name: Prepare variables
      run: |
        RUN_CFG__DOCKER_IMAGE_NAME="tests-${{ matrix.platform }}-py${{ matrix.python }}-pg${{ matrix.postgres }}"
        echo "RUN_CFG__DOCKER_IMAGE_NAME=$RUN_CFG__DOCKER_IMAGE_NAME" >> $GITHUB_ENV
        echo "---------- [$GITHUB_ENV]"
        cat $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build local image ${{ matrix.alpine }}
      run: docker build --build-arg PG_VERSION="${{ matrix.postgres }}" --build-arg PYTHON_VERSION="${{ matrix.python }}" -t "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}" -f Dockerfile--${{ matrix.platform }}.tmpl .
    - name: Run
      run: docker run $(bash <(curl -s https://codecov.io/env)) -t "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}"
